# Generated by Django 2.1.3 on 2018-11-16 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text="Tworząc nową klasę, zaznacz role w polu 'rekrutacja'.", max_length=50, null=True, unique=True)),
                ('icon', models.ImageField(blank=True, upload_to='class_icons')),
                ('tank', models.BooleanField(default=False)),
                ('heal', models.BooleanField(default=False)),
                ('melee', models.BooleanField(default=False)),
                ('ranged', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Klasy',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Rekrutacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank', models.BooleanField(default=False)),
                ('heal', models.BooleanField(default=False)),
                ('melee', models.BooleanField(default=False)),
                ('ranged', models.BooleanField(default=False)),
                ('klasa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.Klasa')),
            ],
            options={
                'verbose_name_plural': 'Rekrutacja',
                'ordering': ('klasa',),
            },
        ),
    ]
