# Generated by Django 2.1.3 on 2018-11-06 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rekrutacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekrutacjaTank', models.BooleanField()),
                ('rekrutacjaHeal', models.BooleanField()),
                ('rekrutacjaMelee', models.BooleanField()),
                ('rekrutacjaRanged', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Rekrutacja',
            },
        ),
        migrations.AlterModelOptions(
            name='klasa',
            options={'verbose_name_plural': 'Klasy'},
        ),
        migrations.AddField(
            model_name='rekrutacja',
            name='klasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Klasa'),
        ),
    ]
