# Generated by Django 2.1.3 on 2018-11-16 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Killshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.CharField(blank=True, default='', max_length=50, null=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='killshots')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
