# Generated by Django 2.1.3 on 2018-11-07 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181106_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekrutacja',
            name='klasa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.Klasa'),
        ),
        migrations.AlterField(
            model_name='rekrutacja',
            name='rekrutacjaHeal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rekrutacja',
            name='rekrutacjaMelee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rekrutacja',
            name='rekrutacjaRanged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rekrutacja',
            name='rekrutacjaTank',
            field=models.BooleanField(default=False),
        ),
    ]
