# Generated by Django 2.1.3 on 2018-11-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20181107_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasa',
            name='heal',
            field=models.BooleanField(default=False, unique=True),
        ),
        migrations.AlterField(
            model_name='klasa',
            name='melee',
            field=models.BooleanField(default=False, unique=True),
        ),
        migrations.AlterField(
            model_name='klasa',
            name='ranged',
            field=models.BooleanField(default=False, unique=True),
        ),
        migrations.AlterField(
            model_name='klasa',
            name='tank',
            field=models.BooleanField(default=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rekrutacja',
            name='heal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekrutacjaHeal', to='pages.Klasa', to_field='heal'),
        ),
        migrations.AlterField(
            model_name='rekrutacja',
            name='melee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekrutacjaMelee', to='pages.Klasa', to_field='melee'),
        ),
        migrations.AlterField(
            model_name='rekrutacja',
            name='ranged',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekrutacjaRanged', to='pages.Klasa', to_field='ranged'),
        ),
        migrations.AlterField(
            model_name='rekrutacja',
            name='tank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekrutacjaTank', to='pages.Klasa', to_field='tank'),
        ),
    ]
