# Generated by Django 2.1.3 on 2018-11-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20181107_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasa',
            name='heal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='klasa',
            name='melee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='klasa',
            name='ranged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='klasa',
            name='tank',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rekrutacja',
            name='heal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rekrutacja',
            name='melee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rekrutacja',
            name='ranged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rekrutacja',
            name='tank',
            field=models.BooleanField(default=False),
        ),
    ]
