# Generated by Django 2.1.3 on 2018-11-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20181107_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasa',
            name='name',
            field=models.CharField(help_text="Tworząc nową klasę, zaznacz role w polu 'rekrutacja'.", max_length=50, unique=True),
        ),
    ]
