# Generated by Django 2.1.3 on 2018-11-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20181107_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klasa',
            options={'ordering': ('name',), 'verbose_name_plural': 'Klasy'},
        ),
        migrations.AlterModelOptions(
            name='rekrutacja',
            options={'ordering': ('klasa',), 'verbose_name_plural': 'Rekrutacja'},
        ),
    ]
