# Generated by Django 2.1.3 on 2018-11-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20181107_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasa',
            name='icon',
            field=models.ImageField(blank=True, upload_to='class_icons'),
        ),
    ]
