# Generated by Django 2.1.3 on 2018-11-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_klasa_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasa',
            name='name',
            field=models.CharField(default='', help_text="Tworząc nową klasę, zaznacz role w polu 'rekrutacja'.", max_length=50, unique=True),
        ),
    ]
