# Generated by Django 2.1.3 on 2018-12-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('kiedy', models.DateTimeField()),
                ('opis', models.TextField(max_length=500)),
                ('miejsca', models.PositiveIntegerField(blank=True, default=30, null=True)),
                ('usuniety', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wymagania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Wymagania',
            },
        ),
    ]
