# Generated by Django 2.1.3 on 2018-12-07 11:08

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='kiedy',
        ),
        migrations.AddField(
            model_name='event',
            name='alty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='kiedy_dzien',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='kiedy_godzina',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='odblokuj_zapisy',
            field=models.BooleanField(default=False),
        ),
    ]
