# Generated by Django 2.1.3 on 2018-12-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0002_auto_20181207_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('kiedy_dzien', 'kiedy_godzina')},
        ),
    ]
