# Generated by Django 2.1.3 on 2018-12-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0004_zapis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapis',
            name='komentarz',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
