# Generated by Django 2.1.3 on 2018-12-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0006_zapis_wybrany'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapis',
            name='anulowany',
            field=models.BooleanField(default=False),
        ),
    ]
