# Generated by Django 2.1.3 on 2018-12-13 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0007_zapis_anulowany'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBlueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaSzablonu', models.CharField(max_length=50)),
                ('nazwaEventu', models.CharField(max_length=50)),
                ('kiedy_godzina', models.TimeField(default=datetime.time(20, 0))),
                ('opis', models.TextField(max_length=500)),
                ('miejsca', models.PositiveIntegerField(blank=True, default=30, null=True)),
                ('alty', models.BooleanField(default=False)),
            ],
        ),
    ]
