# Generated by Django 2.1.3 on 2018-11-13 12:04

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '__first__'),
        ('rejestracja', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_main', models.BooleanField(default=False)),
                ('klasa', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='postacKlasa', to='pages.Klasa')),
                ('mainspec', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='postacMainspec', to='rejestracja.Rola')),
                ('offspec', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='postacOffspec', to='rejestracja.Rola')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rasa', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='postacRasa', to='rejestracja.Rasa')),
                ('serwer', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='postacSerwer', to='rejestracja.Serwer')),
            ],
            options={
                'verbose_name_plural': 'Postacie Userów',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='Niepoprawny numer telefonu', message='Sprawdź poprawność numeru telefonu', regex='[0-9]{9,12}')])),
                ('battleTag', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='Niepoprawny battleTag', message='Sprawdź poprawność battleTaga', regex='[A-Za-z0-9]+#[0-9]{4,}$')])),
                ('email', models.EmailField(max_length=125)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile Użytkowników',
            },
        ),
    ]
