# Generated by Django 2.1.3 on 2018-11-16 12:21

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rejestracja.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('infoRaidDoswiadczenie', models.TextField(blank=True, max_length=700)),
                ('infoRaidWiedza', models.TextField(blank=True, max_length=700)),
                ('infoRaidDni', models.TextField(blank=True, max_length=700)),
                ('infoGildie', models.TextField(max_length=700)),
                ('infoOgolne', models.TextField(max_length=700)),
                ('plec', models.CharField(blank=True, choices=[('K', 'K'), ('M', 'M'), ('-', '-')], max_length=2, null=True)),
                ('battleTag', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='Niepoprawny battleTag', message='Sprawdź poprawność battleTaga', regex='[A-Za-z0-9]+#[0-9]{4,}$')])),
                ('email', models.EmailField(max_length=125)),
                ('emailConfirm', models.EmailField(max_length=125)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('klasa', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pages.Klasa')),
            ],
            options={
                'verbose_name_plural': 'Podania',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PodanieKomentarze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1024)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(default='', on_delete=models.SET(rejestracja.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('podanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rejestracja.Podanie')),
            ],
            options={
                'verbose_name_plural': 'PodanieKomentarze',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Rasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Rasy',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Rola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Role',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Serwer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Serwery',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='podanie',
            name='mainspec',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mainspec', to='rejestracja.Rola'),
        ),
        migrations.AddField(
            model_name='podanie',
            name='offspec',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='offspec', to='rejestracja.Rola'),
        ),
        migrations.AddField(
            model_name='podanie',
            name='rasa',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rejestracja.Rasa'),
        ),
        migrations.AddField(
            model_name='podanie',
            name='serwer',
            field=models.ForeignKey(default='', on_delete=models.SET(rejestracja.models.get_sentinel_serwer), to='rejestracja.Serwer'),
        ),
    ]
