# Generated by Django 2.1.3 on 2018-11-09 09:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0011_auto_20181109_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('infoRaidDoswiadczenie', models.TextField(max_length=1024)),
                ('infoRaidWiedza', models.TextField(max_length=1024)),
                ('infoRaidDni', models.TextField(max_length=1024)),
                ('infoGildie', models.TextField(max_length=1024)),
                ('infoOgolne', models.TextField(max_length=1024)),
                ('plec', models.CharField(choices=[('K', 'K'), ('M', 'M')], max_length=2)),
                ('battleTag', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=125)),
                ('emailConfirm', models.EmailField(max_length=125)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('klasa', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='pages.Klasa')),
            ],
            options={
                'verbose_name_plural': 'Podania',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Rasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Rasy',
            },
        ),
        migrations.CreateModel(
            name='Rola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Serwer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Serwery',
            },
        ),
        migrations.AddField(
            model_name='podanie',
            name='mainspec',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mainspec', to='rejestracja.Rola'),
        ),
        migrations.AddField(
            model_name='podanie',
            name='offspec',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='offspec', to='rejestracja.Rola'),
        ),
        migrations.AddField(
            model_name='podanie',
            name='rasa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='rejestracja.Rasa'),
        ),
        migrations.AddField(
            model_name='podanie',
            name='serwer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='rejestracja.Serwer'),
        ),
    ]
