# Generated by Django 2.1.3 on 2018-11-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestracja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podanie',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podanie',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
