# Generated by Django 2.1.3 on 2018-11-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestracja', '0002_auto_20181109_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podanie',
            name='infoRaidDni',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='podanie',
            name='infoRaidDoswiadczenie',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='podanie',
            name='infoRaidWiedza',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
