# Generated by Django 2.1.3 on 2018-11-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejestracja', '0002_auto_20181116_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podanie',
            options={'ordering': ('date',), 'verbose_name_plural': 'Podania'},
        ),
    ]
