# Generated by Django 2.1.3 on 2018-11-09 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestracja', '0005_auto_20181109_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podaniekomentarze',
            options={'ordering': ('-date',), 'verbose_name_plural': 'PodanieKomentarze'},
        ),
        migrations.AddField(
            model_name='podaniekomentarze',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
