# Generated by Django 2.1.3 on 2018-11-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rejestracja', '0006_auto_20181109_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podanie',
            name='infoGildie',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='podanie',
            name='infoOgolne',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='podanie',
            name='infoRaidDni',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='podanie',
            name='infoRaidDoswiadczenie',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='podanie',
            name='infoRaidWiedza',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='podanie',
            name='serwer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rejestracja.Serwer'),
        ),
    ]
