# Generated by Django 2.1.3 on 2018-11-12 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rejestracja', '0008_auto_20181112_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podanie',
            name='klasa',
            field=models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pages.Klasa'),
        ),
        migrations.AlterField(
            model_name='podanie',
            name='mainspec',
            field=models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mainspec', to='rejestracja.Rola'),
        ),
        migrations.AlterField(
            model_name='podanie',
            name='offspec',
            field=models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='offspec', to='rejestracja.Rola'),
        ),
        migrations.AlterField(
            model_name='podanie',
            name='plec',
            field=models.CharField(blank=True, choices=[('K', 'K'), ('M', 'M'), ('-', '-')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='podanie',
            name='rasa',
            field=models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rejestracja.Rasa'),
        ),
        migrations.AlterField(
            model_name='podanie',
            name='serwer',
            field=models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rejestracja.Serwer'),
        ),
    ]
