# Generated by Django 2.1.3 on 2018-11-12 08:41

from django.db import migrations, models
import rejestracja.models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestracja', '0010_auto_20181112_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podanie',
            name='serwer',
            field=models.ForeignKey(default='', on_delete=models.SET(rejestracja.models.get_sentinel_serwer), to='rejestracja.Serwer'),
        ),
    ]
