# Generated by Django 2.1.3 on 2018-11-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'ordering': ('position',), 'verbose_name_plural': 'Boss'},
        ),
        migrations.AddField(
            model_name='boss',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
