# Generated by Django 2.1.3 on 2018-11-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20181122_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='expansion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raid',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
