# Generated by Django 2.1.3 on 2018-11-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_auto_20181122_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='expansion',
            field=models.PositiveIntegerField(blank=True, help_text='0-Vanilla, 1-TBC, 2-WotLK, 3-Cata, 4-MoP, 5-WoD, 6-Legion, 7-BfA, itd.', null=True),
        ),
    ]
