# Generated by Django 2.1.3 on 2018-11-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_auto_20181122_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='is_current',
        ),
        migrations.AddField(
            model_name='raid',
            name='aktualny',
            field=models.BooleanField(default=False, help_text='Zaznacz, jeśli raid jest aktualnie progresowany'),
        ),
    ]
