# Generated by Django 2.1.3 on 2018-11-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_auto_20181122_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.PositiveIntegerField(blank=True, help_text='0-Vanilla, 1-TBC, 2-WotLK, 3-Cata, 4-MoP, 5-WoD, 6-Legion, 7-BfA, itd.', null=True)),
            ],
            options={
                'verbose_name_plural': 'Expansions',
                'ordering': ('position',),
            },
        ),
        migrations.AlterField(
            model_name='raid',
            name='expansion',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raids', to='progress.Expansion'),
        ),
    ]
