# Generated by Django 2.1.3 on 2018-11-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_raid_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raid',
            options={'ordering': ('position',), 'verbose_name_plural': 'Raids'},
        ),
    ]
