# Generated by Django 2.1.3 on 2018-11-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0008_auto_20181122_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansion',
            name='aktualny',
            field=models.BooleanField(default=False, help_text='Zaznacz, jeśli ten dodatek jest aktualnie progressowany'),
        ),
    ]
